### PR TITLE
Change parameters to the Github Action.

### PR DESCRIPTION
**Pull request by thomaspoignant**
This pull request is changing the parameters to pass to the GitHub Action to map the one from the docker image.
This also does remove the script since we can use the docker image directly.

_I haven't test the GHA, so we may have to test it before merging it._

### CODE REVIEW

**Comment by sarvsav** [comment]
We are seeing below error while testing:

Verification job: [Link](https://github.com/sarvsav/codingtherightway-ff/actions/runs/4865356259/jobs/8675553498)

```text
Error: go-feature-flag/gofeatureflag-lint-action/364be35fa3b0b9af7f95afbcd400984712a9830d/action.yml (Line: 19, Col: 3): Unexpected value 'volumes'
Error: go-feature-flag/gofeatureflag-lint-action/364be35fa3b0b9af7f95afbcd400984712a9830d/action.yml (Line: 19, Col: 3): Unexpected value 'volumes'
```

**Comment by thomaspoignant** [comment]
I am not sure how to mount the volumes 😕

I’ll have a look when I am on my computer.

**Comment by sarvsav** [comment]
Unfortunately, I am afraid to say that volumes may not be available for Docker container action :( as per this documentation: [Docker container action](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions).

**Comment by thomaspoignant** [comment]
Closing this one, I think yours is even better.

**Pull request closed without merging**
